apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: innovatech
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root1234"
  MYSQL_DATABASE: "despachos_db"
  MYSQL_USER: "appuser"
  MYSQL_PASSWORD: "apppass123"
